services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
    volumes:
      - ./frontend:/app
    networks:
      - network

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    command: [ "sh", "-c", "npm install && npm run dev" ]
    volumes:
      - ./api:/app
    networks:
      - network

  websocket:
    build:
      context: ./websocket
      dockerfile: ../docker/websocket/Dockerfile
    command: ["sh", "-c", "npm install && node index.js"]
    volumes:
      - ./websocket:/app
    networks:
      - network

  nginx:
    image: nginx:1.17
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT}:80
    networks:
      - network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network
networks:
  network:

volumes:
  mysql_data: